export interface FellowshipProgram {
  name: string;
  institution: string;
  city: string;
  state: string;
  lat: number;
  lng: number;
  url: string;
  rank?: number; // Approximate Doximity reputation ranking — may not be current
  director?: string;
  directorEmail?: string;
}

export interface StateMarker {
  state: string;
  city: string;
  lat: number;
  lng: number;
}

// Rankings are approximate Doximity reputation-based rankings.
// Director names and emails are from training data and may be outdated.
// Verify current details on each program's website.
export const fellowshipPrograms: FellowshipProgram[] = [
  // Alabama
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Alabama at Birmingham",
    city: "Birmingham",
    state: "AL",
    lat: 33.5019,
    lng: -86.8063,
    url: "https://www.uab.edu/medicine/obgyn/gynecologic-oncology/fellowship",
    rank: 15,
    director: "Warner Huh, MD",
    directorEmail: "whuh@uabmc.edu",
  },
  // Arizona
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Arizona College of Medicine",
    city: "Phoenix",
    state: "AZ",
    lat: 33.4580,
    lng: -112.0740,
    url: "https://obgyn.arizona.edu/gynecologic-oncology-fellowship",
    rank: 40,
  },
  // California
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "City of Hope National Medical Center",
    city: "Duarte",
    state: "CA",
    lat: 34.1395,
    lng: -117.9720,
    url: "https://www.cityofhope.org/education/graduate-medical-education/gynecologic-oncology-fellowship",
    rank: 30,
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Cedars-Sinai Medical Center",
    city: "Los Angeles",
    state: "CA",
    lat: 34.0754,
    lng: -118.3802,
    url: "https://www.cedars-sinai.org/education/graduate-medical-education/fellowship/gynecologic-oncology.html",
    rank: 22,
    director: "Bobbie Rimel, MD",
    directorEmail: "bobbie.rimel@cshs.org",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Stanford University",
    city: "Stanford",
    state: "CA",
    lat: 37.4322,
    lng: -122.1750,
    url: "https://med.stanford.edu/obgyn/education/fellowship/gynecologic-oncology.html",
    rank: 8,
    director: "Oliver Dorigo, MD, PhD",
    directorEmail: "odorigo@stanford.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "UC Irvine Medical Center",
    city: "Orange",
    state: "CA",
    lat: 33.7879,
    lng: -117.8531,
    url: "https://www.obgyn.uci.edu/fellowship/gynecologic-oncology",
    rank: 28,
    director: "Krishnansu Tewari, MD",
    directorEmail: "ktewari@uci.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "UCLA David Geffen School of Medicine",
    city: "Los Angeles",
    state: "CA",
    lat: 34.0661,
    lng: -118.4468,
    url: "https://www.uclahealth.org/departments/obgyn/education/fellowships/gynecologic-oncology-fellowship",
    rank: 10,
    director: "Sanaz Memarzadeh, MD, PhD",
    directorEmail: "smemarzadeh@mednet.ucla.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "UC San Francisco",
    city: "San Francisco",
    state: "CA",
    lat: 37.7631,
    lng: -122.4576,
    url: "https://obgyn.ucsf.edu/gynecologic-oncology/fellowship",
    rank: 9,
    director: "Lee-may Chen, MD",
    directorEmail: "lee-may.chen@ucsf.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "UC Davis Medical Center",
    city: "Sacramento",
    state: "CA",
    lat: 38.5537,
    lng: -121.4537,
    url: "https://health.ucdavis.edu/obgyn/fellowships/gynecologic_oncology/",
    rank: 38,
    director: "Gary Leiserowitz, MD",
    directorEmail: "gary.leiserowitz@ucdmc.ucdavis.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "UC San Diego Medical Center",
    city: "La Jolla",
    state: "CA",
    lat: 32.8801,
    lng: -117.2340,
    url: "https://medschool.ucsd.edu/som/obgyn/education/fellowship/gynecologic-oncology/",
    rank: 25,
    director: "Steven Plaxe, MD",
    directorEmail: "splaxe@ucsd.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Southern California",
    city: "Los Angeles",
    state: "CA",
    lat: 34.0623,
    lng: -118.2057,
    url: "https://keck.usc.edu/obstetrics-gynecology/education-training/fellowships/gynecologic-oncology/",
    rank: 14,
    director: "Koji Matsuo, MD, PhD",
    directorEmail: "koji.matsuo@med.usc.edu",
  },
  // Colorado
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Colorado",
    city: "Aurora",
    state: "CO",
    lat: 39.7454,
    lng: -104.8387,
    url: "https://medschool.cuanschutz.edu/obgyn/education-and-training/fellowships/gynecologic-oncology",
    rank: 20,
    director: "Saketh Guntupalli, MD",
    directorEmail: "saketh.guntupalli@cuanschutz.edu",
  },
  // Connecticut
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Yale School of Medicine",
    city: "New Haven",
    state: "CT",
    lat: 41.3032,
    lng: -72.9364,
    url: "https://medicine.yale.edu/obgyn/education/fellowships/gynecologic-oncology/",
    rank: 11,
    director: "Alessandro Santin, MD",
    directorEmail: "alessandro.santin@yale.edu",
  },
  // Florida
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Moffitt Cancer Center / University of South Florida",
    city: "Tampa",
    state: "FL",
    lat: 28.0653,
    lng: -82.4319,
    url: "https://moffitt.org/research-science/education-training/graduate-medical-education/gynecologic-oncology-fellowship/",
    rank: 16,
    director: "Robert Wenham, MD",
    directorEmail: "robert.wenham@moffitt.org",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Florida College of Medicine",
    city: "Gainesville",
    state: "FL",
    lat: 29.6400,
    lng: -82.3436,
    url: "https://obgyn.med.ufl.edu/education/fellowships/gynecologic-oncology/",
    rank: 35,
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Miami Miller School of Medicine",
    city: "Miami",
    state: "FL",
    lat: 25.7903,
    lng: -80.2101,
    url: "https://obgyn.med.miami.edu/education/fellowship-programs/gynecologic-oncology",
    rank: 32,
    director: "Matthew Schlumbrecht, MD",
    directorEmail: "mschlumbrecht@med.miami.edu",
  },
  // Georgia
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Emory University School of Medicine",
    city: "Atlanta",
    state: "GA",
    lat: 33.7945,
    lng: -84.3236,
    url: "https://www.emory.edu/gynob/fellowship/gynecologic-oncology",
    rank: 18,
    director: "Namita Khanna, MD",
    directorEmail: "namita.khanna@emory.edu",
  },
  // Illinois
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Northwestern University Feinberg School of Medicine",
    city: "Chicago",
    state: "IL",
    lat: 41.8953,
    lng: -87.6171,
    url: "https://www.feinberg.northwestern.edu/sites/obgyn/education/fellowship/gynecologic-oncology/",
    rank: 7,
    director: "Nikki Neubauer, MD",
    directorEmail: "nikki.neubauer@nm.org",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Chicago",
    city: "Chicago",
    state: "IL",
    lat: 41.7894,
    lng: -87.6048,
    url: "https://www.uchicagomedicine.org/obgyn/education/fellowship-programs/gynecologic-oncology",
    rank: 13,
    director: "S. Diane Yamada, MD",
    directorEmail: "sdyamada@bsd.uchicago.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Loyola University Medical Center",
    city: "Maywood",
    state: "IL",
    lat: 41.8796,
    lng: -87.8432,
    url: "https://ssom.luc.edu/obgyn/fellowships/gynecologiconcology/",
    rank: 42,
  },
  // Indiana
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Indiana University School of Medicine",
    city: "Indianapolis",
    state: "IN",
    lat: 39.7797,
    lng: -86.1771,
    url: "https://medicine.iu.edu/obgyn/education/fellowships/gynecologic-oncology",
    rank: 27,
  },
  // Iowa
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Iowa Hospitals and Clinics",
    city: "Iowa City",
    state: "IA",
    lat: 41.6609,
    lng: -91.5468,
    url: "https://uihc.org/gynecologic-oncology-fellowship",
    rank: 24,
    director: "David Bender, MD",
    directorEmail: "david-bender@uiowa.edu",
  },
  // Kentucky
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Kentucky College of Medicine",
    city: "Lexington",
    state: "KY",
    lat: 38.0311,
    lng: -84.5085,
    url: "https://obgyn.med.uky.edu/gynecologic-oncology-fellowship",
    rank: 36,
    director: "Frederick Ueland, MD",
    directorEmail: "fuela0@uky.edu",
  },
  // Maryland
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Johns Hopkins University School of Medicine",
    city: "Baltimore",
    state: "MD",
    lat: 39.2966,
    lng: -76.5926,
    url: "https://www.hopkinsmedicine.org/gynecology-obstetrics/education/fellowships/gynecologic-oncology",
    rank: 2,
    director: "Amanda Nickles Fader, MD",
    directorEmail: "afader1@jhmi.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Walter Reed National Military Medical Center",
    city: "Bethesda",
    state: "MD",
    lat: 39.0000,
    lng: -77.0945,
    url: "https://www.wrnmmc.health.mil/Education/Graduate-Medical-Education/",
    rank: 45,
  },
  // Massachusetts
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Brigham and Women's Hospital / Harvard Medical School",
    city: "Boston",
    state: "MA",
    lat: 42.3357,
    lng: -71.1068,
    url: "https://www.brighamandwomens.org/obgyn/oncology/gynecologic-oncology-fellowship",
    rank: 3,
    director: "Colleen Feltmate, MD",
    directorEmail: "cfeltmate@bwh.harvard.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Massachusetts General Hospital / Harvard Medical School",
    city: "Boston",
    state: "MA",
    lat: 42.3630,
    lng: -71.0686,
    url: "https://www.massgeneral.org/obgyn/education-and-training/gynecologic-oncology-fellowship",
    rank: 4,
    director: "Whitfield Growdon, MD",
    directorEmail: "wgrowdon@mgh.harvard.edu",
  },
  // Michigan
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Michigan",
    city: "Ann Arbor",
    state: "MI",
    lat: 42.2828,
    lng: -83.7312,
    url: "https://medicine.umich.edu/dept/obgyn/education/fellowship-programs/gynecologic-oncology-fellowship",
    rank: 12,
    director: "Carolyn Johnston, MD",
    directorEmail: "johnstca@med.umich.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Wayne State University / Karmanos Cancer Institute",
    city: "Detroit",
    state: "MI",
    lat: 42.3558,
    lng: -83.0575,
    url: "https://obgyn.med.wayne.edu/fellowships/gynecologic-oncology",
    rank: 43,
    director: "Robert Morris, MD",
    directorEmail: "rmorris@med.wayne.edu",
  },
  // Minnesota
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Mayo Clinic",
    city: "Rochester",
    state: "MN",
    lat: 44.0234,
    lng: -92.4630,
    url: "https://college.mayo.edu/academics/residencies-and-fellowships/gynecologic-oncology-fellowship-minnesota/",
    rank: 5,
    director: "Jamie Bakkum-Gamez, MD",
    directorEmail: "bakkum.jamie@mayo.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Minnesota",
    city: "Minneapolis",
    state: "MN",
    lat: 44.9719,
    lng: -93.2578,
    url: "https://med.umn.edu/obgyn/education/fellowship-programs/gynecologic-oncology",
    rank: 29,
    director: "Peter Argenta, MD",
    directorEmail: "argenta@umn.edu",
  },
  // Missouri
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Washington University School of Medicine in St. Louis",
    city: "St. Louis",
    state: "MO",
    lat: 38.6354,
    lng: -90.2635,
    url: "https://obgyn.wustl.edu/education-training/fellowships/gynecologic-oncology/",
    rank: 17,
    director: "Premal Thaker, MD",
    directorEmail: "thakerp@wustl.edu",
  },
  // New Jersey
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Rutgers Robert Wood Johnson Medical School",
    city: "New Brunswick",
    state: "NJ",
    lat: 40.4969,
    lng: -74.4465,
    url: "https://rwjms.rutgers.edu/departments/obstetrics-gynecology-and-reproductive-sciences/fellowship/gynecologic_oncology",
    rank: 37,
  },
  // New York
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Memorial Sloan Kettering Cancer Center",
    city: "New York",
    state: "NY",
    lat: 40.7642,
    lng: -73.9575,
    url: "https://www.mskcc.org/hcp-education-training/fellowships/gynecologic-oncology-fellowship",
    rank: 1,
    director: "Nadeem Abu-Rustum, MD",
    directorEmail: "abu-rusn@mskcc.org",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Columbia University Irving Medical Center",
    city: "New York",
    state: "NY",
    lat: 40.8422,
    lng: -73.9418,
    url: "https://www.obgyn.columbia.edu/education-and-training/fellowship-programs/gynecologic-oncology",
    rank: 6,
    director: "Jason Wright, MD",
    directorEmail: "jw2459@cumc.columbia.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "NYU Grossman School of Medicine",
    city: "New York",
    state: "NY",
    lat: 40.7421,
    lng: -73.9746,
    url: "https://med.nyu.edu/departments-institutes/obstetrics-gynecology/education/fellowship-programs/gynecologic-oncology-fellowship",
    rank: 19,
    director: "Bhavana Pothuri, MD",
    directorEmail: "bhavana.pothuri@nyulangone.org",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Weill Cornell Medicine / NewYork-Presbyterian",
    city: "New York",
    state: "NY",
    lat: 40.7650,
    lng: -73.9543,
    url: "https://obgyn.weill.cornell.edu/education/fellowships/gynecologic-oncology",
    rank: 21,
    director: "Kevin Holcomb, MD",
    directorEmail: "keh2003@med.cornell.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Roswell Park Comprehensive Cancer Center / University at Buffalo",
    city: "Buffalo",
    state: "NY",
    lat: 42.8998,
    lng: -78.8453,
    url: "https://www.roswellpark.org/education/gynecologic-oncology-fellowship",
    rank: 34,
    director: "Emese Zsiros, MD, PhD",
    directorEmail: "emese.zsiros@roswellpark.org",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Northwell Health",
    city: "New Hyde Park",
    state: "NY",
    lat: 40.7357,
    lng: -73.6879,
    url: "https://www.northwell.edu/obstetrics-and-gynecology/education-research/fellowship-programs/gynecologic-oncology-fellowship",
    rank: 33,
  },
  // North Carolina
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Duke University Medical Center",
    city: "Durham",
    state: "NC",
    lat: 36.0078,
    lng: -78.9385,
    url: "https://obgyn.duke.edu/education-and-training/fellowship-programs/gynecologic-oncology-fellowship",
    rank: 6,
    director: "Angeles Alvarez Secord, MD",
    directorEmail: "angeles.secord@duke.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of North Carolina at Chapel Hill",
    city: "Chapel Hill",
    state: "NC",
    lat: 35.9050,
    lng: -79.0469,
    url: "https://www.med.unc.edu/obgyn/divisions/gyn-oncology/fellowship/",
    rank: 16,
    director: "Paola Gehrig, MD",
    directorEmail: "paola_gehrig@med.unc.edu",
  },
  // Ohio
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Cleveland Clinic Foundation",
    city: "Cleveland",
    state: "OH",
    lat: 41.5015,
    lng: -81.6219,
    url: "https://my.clevelandclinic.org/departments/obgyn-womens-health/medical-professionals/fellowship/gynecologic-oncology",
    rank: 23,
    director: "Peter Rose, MD",
    directorEmail: "rosep@ccf.org",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "The Ohio State University Wexner Medical Center",
    city: "Columbus",
    state: "OH",
    lat: 39.9945,
    lng: -83.0181,
    url: "https://wexnermedical.osu.edu/obstetrics-gynecology/gynecologic-oncology/fellowship",
    rank: 19,
    director: "Floor Backes, MD",
    directorEmail: "floor.backes@osumc.edu",
  },
  // Oklahoma
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Oklahoma Health Sciences Center",
    city: "Oklahoma City",
    state: "OK",
    lat: 35.4819,
    lng: -97.4966,
    url: "https://obgyn.ouhsc.edu/Fellowships/GynecologicOncology",
    rank: 26,
    director: "Kathleen Moore, MD",
    directorEmail: "kathleen-moore@ouhsc.edu",
  },
  // Oregon
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Oregon Health & Science University",
    city: "Portland",
    state: "OR",
    lat: 45.4990,
    lng: -122.6855,
    url: "https://www.ohsu.edu/school-of-medicine/obstetrics-and-gynecology/gynecologic-oncology-fellowship",
    rank: 31,
    director: "Tanja Pejovic, MD, PhD",
    directorEmail: "pejovict@ohsu.edu",
  },
  // Pennsylvania
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Hospital of the University of Pennsylvania",
    city: "Philadelphia",
    state: "PA",
    lat: 39.9494,
    lng: -75.1933,
    url: "https://www.pennmedicine.org/departments-and-centers/department-of-obstetrics-and-gynecology/education-and-training/fellowship-programs/gynecologic-oncology-fellowship",
    rank: 5,
    director: "Emily Ko, MD",
    directorEmail: "emily.ko@pennmedicine.upenn.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Magee-Womens Hospital / University of Pittsburgh",
    city: "Pittsburgh",
    state: "PA",
    lat: 40.4369,
    lng: -79.9614,
    url: "https://www.mageewomens.org/education/fellowships/gynecologic-oncology-fellowship",
    rank: 21,
    director: "Alexander Olawaiye, MD",
    directorEmail: "olawaiyeab@upmc.edu",
  },
  // South Carolina
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Medical University of South Carolina",
    city: "Charleston",
    state: "SC",
    lat: 32.7842,
    lng: -79.9467,
    url: "https://medicine.musc.edu/departments/obgyn/divisions/gyn-oncology/fellowship",
    rank: 39,
  },
  // Rhode Island
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Women & Infants Hospital / Brown University",
    city: "Providence",
    state: "RI",
    lat: 41.8141,
    lng: -71.4125,
    url: "https://www.womenandinfants.org/education/fellowship-programs/gynecologic-oncology",
    rank: 26,
    director: "Richard Moore, MD",
    directorEmail: "rmoore@wihri.org",
  },
  // Tennessee
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Vanderbilt University Medical Center",
    city: "Nashville",
    state: "TN",
    lat: 36.1417,
    lng: -86.8011,
    url: "https://www.vumc.org/obgyn/gynecologic-oncology-fellowship",
    rank: 18,
    director: "Dineo Khabele, MD",
    directorEmail: "dineo.khabele@vumc.org",
  },
  // Texas
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "MD Anderson Cancer Center / University of Texas",
    city: "Houston",
    state: "TX",
    lat: 29.7073,
    lng: -95.3972,
    url: "https://www.mdanderson.org/education-training/clinical-research-training/graduate-medical-education/fellowships-and-programs/gynecologic-oncology-fellowship.html",
    rank: 1,
    director: "Pedro Ramirez, MD",
    directorEmail: "pramirez@mdanderson.org",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Baylor College of Medicine",
    city: "Houston",
    state: "TX",
    lat: 29.7104,
    lng: -95.3975,
    url: "https://www.bcm.edu/departments/obstetrics-and-gynecology/education/fellowships/gynecologic-oncology",
    rank: 29,
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "UT Southwestern Medical Center",
    city: "Dallas",
    state: "TX",
    lat: 32.8129,
    lng: -96.8414,
    url: "https://utswmed.org/medblog/gyn-oncology-fellowship/",
    rank: 14,
    director: "Jayanthi Lea, MD",
    directorEmail: "jayanthi.lea@utsouthwestern.edu",
  },
  // Virginia
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Virginia Health System",
    city: "Charlottesville",
    state: "VA",
    lat: 38.0334,
    lng: -78.5010,
    url: "https://med.virginia.edu/obgyn/education/fellowship-programs/gynecologic-oncology/",
    rank: 33,
    director: "Linda Duska, MD",
    directorEmail: "lduska@virginia.edu",
  },
  // Washington
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Washington Medical Center",
    city: "Seattle",
    state: "WA",
    lat: 47.6497,
    lng: -122.3076,
    url: "https://obgyn.uw.edu/fellowship-gynecologic-oncology",
    rank: 10,
    director: "Barbara Goff, MD",
    directorEmail: "bgoff@uw.edu",
  },
  // Wisconsin
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "Medical College of Wisconsin",
    city: "Milwaukee",
    state: "WI",
    lat: 43.0451,
    lng: -87.9685,
    url: "https://www.mcw.edu/departments/obstetrics-and-gynecology/education/fellowships/gynecologic-oncology",
    rank: 41,
    director: "William Bradley, MD",
    directorEmail: "wbradley@mcw.edu",
  },
  {
    name: "Gynecologic Oncology Fellowship",
    institution: "University of Wisconsin School of Medicine",
    city: "Madison",
    state: "WI",
    lat: 43.0766,
    lng: -89.4125,
    url: "https://www.obgyn.wisc.edu/education/fellowship-programs/gynecologic-oncology",
    rank: 23,
    director: "Lisa Barroilhet, MD",
    directorEmail: "barroilhet@wisc.edu",
  },
];

// Most populated city in each state that has a fellowship program
export const statePopulationMarkers: StateMarker[] = [
  { state: "AL", city: "Birmingham", lat: 33.5186, lng: -86.8104 },
  { state: "AZ", city: "Phoenix", lat: 33.4484, lng: -112.0740 },
  { state: "CA", city: "Los Angeles", lat: 34.0522, lng: -118.2437 },
  { state: "CO", city: "Denver", lat: 39.7392, lng: -104.9903 },
  { state: "CT", city: "Bridgeport", lat: 41.1865, lng: -73.1952 },
  { state: "FL", city: "Jacksonville", lat: 30.3322, lng: -81.6557 },
  { state: "GA", city: "Atlanta", lat: 33.7490, lng: -84.3880 },
  { state: "IL", city: "Chicago", lat: 41.8781, lng: -87.6298 },
  { state: "IN", city: "Indianapolis", lat: 39.7684, lng: -86.1581 },
  { state: "IA", city: "Des Moines", lat: 41.5868, lng: -93.6250 },
  { state: "KY", city: "Louisville", lat: 38.2527, lng: -85.7585 },
  { state: "MD", city: "Baltimore", lat: 39.2904, lng: -76.6122 },
  { state: "MA", city: "Boston", lat: 42.3601, lng: -71.0589 },
  { state: "MI", city: "Detroit", lat: 42.3314, lng: -83.0458 },
  { state: "MN", city: "Minneapolis", lat: 44.9778, lng: -93.2650 },
  { state: "MO", city: "Kansas City", lat: 39.0997, lng: -94.5786 },
  { state: "NJ", city: "Newark", lat: 40.7357, lng: -74.1724 },
  { state: "NY", city: "New York City", lat: 40.7128, lng: -74.0060 },
  { state: "NC", city: "Charlotte", lat: 35.2271, lng: -80.8431 },
  { state: "OH", city: "Columbus", lat: 39.9612, lng: -82.9988 },
  { state: "OK", city: "Oklahoma City", lat: 35.4676, lng: -97.5164 },
  { state: "OR", city: "Portland", lat: 45.5051, lng: -122.6750 },
  { state: "PA", city: "Philadelphia", lat: 39.9526, lng: -75.1652 },
  { state: "RI", city: "Providence", lat: 41.8240, lng: -71.4128 },
  { state: "SC", city: "Charleston", lat: 32.7765, lng: -79.9311 },
  { state: "TN", city: "Nashville", lat: 36.1627, lng: -86.7816 },
  { state: "TX", city: "Houston", lat: 29.7604, lng: -95.3698 },
  { state: "VA", city: "Virginia Beach", lat: 36.8529, lng: -75.9780 },
  { state: "WA", city: "Seattle", lat: 47.6062, lng: -122.3321 },
  { state: "WI", city: "Milwaukee", lat: 43.0389, lng: -87.9065 },
];
